### ISSUE TITLE
Bug : Javascript dans le profiler de symfony cassé

### ISSUE THREAD

**Issue by MathieM** [MatTheCat/twig-whitespace-collapse-extension#3]
Quand j'active cette extension j'ai une erreur de javascript dans le profiler de symfony.
```
Uncaught SyntaxError: Unexpected end of input
```

Et par exemple dans les form, la possibilité de déplier et replier des blocks n'est plus fonctionelle

Voici le code ou ça bloque : 

```
 if (Sfjs.hasClass(button, 'closed')) { expand(button); } else { collapse(button); } }, initButtons = function (buttons) { states = storage.getItem(STORAGE_KEY, {}); // must be an object, not an array or anything else // `typeof` returns "object" also for arrays, so the following // check must be done
```

Il semblerait que ce soit à cause des commentaires qui se retrouvent sur la même ligne et donc commentent le reste du code.

**Comment by MathieM** [comment]
Après un petit teste il semblerait que cela provienne du premier item des array de preg replace

```
            $node->setAttribute(
                'data',
                preg_replace(
                    array('/\s{2,}/', '/<\s/', '/\s>/'),
                    array(' ', '<', '>'),
                    $text
                )
            );
```

**Comment by MatTheCat** [comment]
Le problème ne vient pas de l'extension qui n'a pas possibilité de savoir si du JavaScript est présent dans du HTML autrement qu'avec un `autoescape`.

La solution serait donc de surcharger le template `@WebProfiler/Collector/form.html.twig` pour lui ajouter ce tag, et éventuellement mentionner le problème côté Symfony.
